/**
 * Gambler Street tuning.
 *
 * This file is the single source of truth for all balance/gameplay knobs of
 * the Gambler Street feature. Tweak values here and rebuild — no code changes
 * required for any of the documented behaviors.
 *
 * Sections:
 *   1. Global parameters (slot count, lifespans, cooldowns, bet tiers, dedupe)
 *   2. Per-treasure tuning (weight, ask amounts, reward curve)
 *   3. Names list (Spanish / Italian / English / German / French)
 *
 * All time values are in milliseconds for direct comparison with `Date.now()`.
 */

import type { TreasureType } from './treasures.ts';

// ─────────────────────────────────────────────────────────────────────────────
// 1. Global parameters
// ─────────────────────────────────────────────────────────────────────────────

export const GAMBLER_STREET_GLOBAL = {
  /** How many gambler slots are visible at once. */
  slotCount: 5,

  /**
   * A new gambler stays around for a random duration in this range before
   * leaving on their own (no bet placed).
   *   [minMs, maxMs] — inclusive min, exclusive max.
   *
   * Tuning note: the brief specified 3–5 min, but in practice that means
   * the carousel "resets" between casual visits. Bumped to 30–60 min so
   * gamblers feel persistent across a play session. Drop back if you want
   * a more frantic rotation.
   */
  lifespanRangeMs: [30 * 60_000, 60 * 60_000] as [number, number],

  /**
   * After a player bets (win OR loss), the slot stays empty for this long
   * before a new gambler appears.
   */
  postBetCooldownMs: 2 * 60_000,

  /**
   * If a gambler leaves on their own (lifespan expired without a bet), the
   * slot only stays empty for this much shorter cooldown.
   */
  expiryCooldownMs: 10_000,

  /**
   * Bet tiers. Both pay the same coin reward on win; they differ in the
   * treasure cost (multiplier on the ask amount) and the win probability.
   * Order matters for UI layout — first tier is "cheap", second is "premium".
   */
  betTiers: {
    cheap: { costMultiplier: 1, winChance: 0.5 },
    premium: { costMultiplier: 2, winChance: 0.75 },
  },

  /**
   * Cap on simultaneous gamblers asking for the same treasure type.
   * E.g. 2 → at most two of the five slots can ask for fish at once.
   */
  maxGamblersPerTreasureType: 2,
} as const;

export type BetTier = keyof typeof GAMBLER_STREET_GLOBAL.betTiers;

// ─────────────────────────────────────────────────────────────────────────────
// 2. Per-treasure tuning
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Per-treasure tuning. A gambler is generated by:
 *   1) picking a treasure type (weighted by `weight`)
 *   2) computing how many of that treasure to ask for:
 *      - if player owns < `amountPctThreshold`:
 *          ask = randomInt(minAmountRange[0], minAmountRange[1])
 *      - else:
 *          ask = owned * randomFloat(amountPctRange[0], amountPctRange[1])
 *      - rounded to nearest `roundAmountTo`, with a floor of `minAmountRange[0]`.
 *   3) computing the coin reward via the diminishing-returns curve below.
 *
 * Reward curve (computed by `computeCoinReward` in GamblerStreetEngine):
 *   marginal rate (coins per +1 unit of treasure) =
 *     - `startRatio` while units ≤ `startUnits`
 *     - log-interpolated between startRatio and endRatio while
 *       `startUnits` < units ≤ `curveMaxUnits`
 *     - `endRatio` while units > curveMaxUnits
 *   total reward = integral of the marginal rate from 0 to N (rounded to nearest 1).
 *
 * Worked example for `fish` with start=200, max=1000, startRatio=0.10, endRatio=0.02:
 *   N=100  → 10 coins      (10:1, full rate)
 *   N=200  → 20 coins      (10:1, full rate at the kink)
 *   N=500  → ≈42 coins
 *   N=1000 → ≈60 coins
 *   N=2000 → ≈80 coins     (tail rate of 50 treasures per 1 coin)
 */
export interface GamblerTreasureTuning {
  /** Probability weight when picking which treasure this gambler wants. */
  weight: number;

  /**
   * When the player owns fewer than `amountPctThreshold` of this type, the
   * gambler asks for a fixed-range absolute amount in [min, max] (inclusive).
   */
  minAmountRange: [number, number];

  /**
   * When the player owns ≥ `amountPctThreshold`, the gambler asks for
   * [min, max] (inclusive) as a fraction of the owned count. Both numbers
   * are decimals, e.g. [0.10, 0.30] = 10%–30% of owned.
   */
  amountPctRange: [number, number];

  /** Switch-over point between absolute and percentage modes. */
  amountPctThreshold: number;

  /** Round the asked amount to the nearest multiple of this. */
  roundAmountTo: number;

  /** Reward curve parameters (see computeCoinReward / class doc above). */
  rewardCurve: {
    /** Coins per unit while at the head of the curve. */
    startRatio: number;
    /** Coins per unit on the tail (asymptotic). */
    endRatio: number;
    /** Below this unit count the rate stays at startRatio. */
    startUnits: number;
    /** At/above this unit count the rate stays at endRatio. */
    curveMaxUnits: number;
  };
}

/**
 * Treasure tunings. The 10 treasure types correspond 1:1 with values in
 * `treasures.ts`. Adjust these freely — they're hot-reloaded on next gambler
 * generation. Common tweaks:
 *   - bump `weight` to make a treasure show up more often
 *   - widen `minAmountRange` to make early-game gamblers more variable
 *   - lower `startRatio` to make a treasure cheap (more units per coin)
 *   - raise `curveMaxUnits` to push out the diminishing-returns kick-in
 */
export const GAMBLER_TREASURE_TUNING: Record<TreasureType, GamblerTreasureTuning> = {
  fish: {
    weight: 100,
    minAmountRange: [20, 100],
    amountPctRange: [0.10, 0.30],
    amountPctThreshold: 50,
    roundAmountTo: 5,
    rewardCurve: {
      startRatio: 0.10,   // 10 fish → 1 coin at the head
      endRatio: 0.02,     // 50 fish → 1 coin on the tail
      startUnits: 200,
      curveMaxUnits: 1000,
    },
  },
  chalice: {
    weight: 70,
    minAmountRange: [5, 30],
    amountPctRange: [0.10, 0.30],
    amountPctThreshold: 30,
    roundAmountTo: 1,
    rewardCurve: {
      startRatio: 0.5,    // 2 chalices → 1 coin
      endRatio: 0.10,     // 10 chalices → 1 coin
      startUnits: 50,
      curveMaxUnits: 300,
    },
  },
  jade: {
    weight: 60,
    minAmountRange: [5, 25],
    amountPctRange: [0.10, 0.30],
    amountPctThreshold: 25,
    roundAmountTo: 1,
    rewardCurve: {
      startRatio: 0.6,
      endRatio: 0.12,
      startUnits: 40,
      curveMaxUnits: 250,
    },
  },
  books: {
    weight: 80,
    minAmountRange: [10, 50],
    amountPctRange: [0.10, 0.30],
    amountPctThreshold: 40,
    roundAmountTo: 5,
    rewardCurve: {
      startRatio: 0.25,
      endRatio: 0.05,
      startUnits: 100,
      curveMaxUnits: 500,
    },
  },
  coffee: {
    weight: 90,
    minAmountRange: [15, 70],
    amountPctRange: [0.10, 0.30],
    amountPctThreshold: 45,
    roundAmountTo: 5,
    rewardCurve: {
      startRatio: 0.18,
      endRatio: 0.04,
      startUnits: 150,
      curveMaxUnits: 700,
    },
  },
  grapes: {
    weight: 85,
    minAmountRange: [15, 60],
    amountPctRange: [0.10, 0.30],
    amountPctThreshold: 40,
    roundAmountTo: 5,
    rewardCurve: {
      startRatio: 0.20,
      endRatio: 0.04,
      startUnits: 120,
      curveMaxUnits: 600,
    },
  },
  lanterns: {
    weight: 65,
    minAmountRange: [5, 25],
    amountPctRange: [0.10, 0.30],
    amountPctThreshold: 25,
    roundAmountTo: 1,
    rewardCurve: {
      startRatio: 0.55,
      endRatio: 0.11,
      startUnits: 45,
      curveMaxUnits: 280,
    },
  },
  bones: {
    weight: 95,
    minAmountRange: [20, 80],
    amountPctRange: [0.10, 0.30],
    amountPctThreshold: 50,
    roundAmountTo: 5,
    rewardCurve: {
      startRatio: 0.12,
      endRatio: 0.025,
      startUnits: 180,
      curveMaxUnits: 900,
    },
  },
  mushrooms: {
    weight: 75,
    minAmountRange: [10, 40],
    amountPctRange: [0.10, 0.30],
    amountPctThreshold: 35,
    roundAmountTo: 5,
    rewardCurve: {
      startRatio: 0.30,
      endRatio: 0.06,
      startUnits: 80,
      curveMaxUnits: 450,
    },
  },
  amulets: {
    weight: 40,
    minAmountRange: [3, 15],
    amountPctRange: [0.10, 0.30],
    amountPctThreshold: 20,
    roundAmountTo: 1,
    rewardCurve: {
      startRatio: 1.0,    // 1 amulet → 1 coin (rare)
      endRatio: 0.20,     // 5 amulets → 1 coin (still valuable on tail)
      startUnits: 25,
      curveMaxUnits: 150,
    },
  },
};

// ─────────────────────────────────────────────────────────────────────────────
// 3. Names list
// ─────────────────────────────────────────────────────────────────────────────

/**
 * Pool of gambler names. Mix of classic European cultures.
 * Add/remove freely — the generator picks one uniformly at random.
 */
export const GAMBLER_NAMES: readonly string[] = [
  // Spanish
  'Diego Vargas', 'Mateo Cruz', 'Lucía Reyes', 'Sofía Ortega', 'Javier Núñez',
  'Carmen Bravo', 'Rafael Mendoza', 'Isabela Soto', 'Tomás Aguilar', 'Elena Pardo',
  // Italian
  'Marco Bellini', 'Giulia Ricci', 'Luca Conti', 'Sofia Gallo', 'Matteo Romano',
  'Chiara Ferrari', 'Alessio De Luca', 'Bianca Marino', 'Vito Esposito', 'Lucia Greco',
  // English
  'Edmund Ashford', 'Margaret Whitfield', 'Henry Blackwood', 'Eleanor Thorne', 'Walter Greaves',
  'Beatrice Holloway', 'Cyril Pemberton', 'Agnes Sutcliffe', 'Reginald Carmichael', 'Mabel Hawthorne',
  // German
  'Friedrich Vogel', 'Klaus Engel', 'Greta Hartmann', 'Otto Reinhardt', 'Hilda Brandt',
  'Wilhelm Krause', 'Anneliese Schäfer', 'Heinrich Bauer', 'Erika Müller', 'Konrad Holz',
  // French
  'Jean-Luc Moreau', 'Étienne Garnier', 'Camille Dubois', 'Henri Lefèvre', 'Margaux Renard',
  'Pierre Marchand', 'Céleste Beaumont', 'Octave Laurent', 'Adèle Charpentier', 'Théo Vidal',
];
